language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - 'node_modules'

before_install:
  - npm i -g npm@latest

before_script:
  - yarn bootstrap

script:
  - yarn build
  - yarn lint
  - yarn test

after_success: yarn coverage

deploy:
  on:
    tags: true
    branch: master
  skip_cleanup: true
  provider: npm
  email: '$NPM_EMAIL_ADDRESS'
  api_key: '$NPM_AUTH_TOKEN'
